version: "3"
services:
  db:
    container_name: db
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: web
    command: poetry run flask run --host=0.0.0.0 --port=8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
