  version: "3"
  services:
    db:
      container_name: pyfsm-db
      image: postgres:12
      env_file:
        - .env
      ports:
        - "5432:5432"
    web:
      build: .
      container_name: pyfsm-web
      command: poetry run flask run --host=0.0.0.0 --port=8000
      env_file:
        - .env
      ports:
        - "8000:8000"
      depends_on:
        - db
    migrations:
      container_name: pyfsm-migrations
      build: .
      command: poetry run python scripts/run-alembic.py
      env_file:
        - .env
      depends_on:
        - db
        - web
