name: Python Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9.16"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Migrate
        run: |
          export FLASK_APP=app:create_app
          export FLASK_DEBUG=1
          export DATABASE_URL=postgresql://srobfcqi:R7qVO3T8-5PLBVIjKIwwmGLmbfINlGv-@babar.db.elephantsql.com/srobfcqi
          export APP_SETTINGS=config.DevelopmentConfig
          python scripts/run-alembic.py upgrade head
      - name: Test
        run: |
          export FLASK_APP=app:create_app
          export FLASK_DEBUG=1
          export DATABASE_URL=postgresql://srobfcqi:R7qVO3T8-5PLBVIjKIwwmGLmbfINlGv-@babar.db.elephantsql.com/srobfcqi
          python -m unittest discover -s . -v
